# The top-level key must be `services` for a Blueprint.
services:

  # Define your Flask Web Service
  - type: web
    name: fweb
    env: python
    repo: https://github.com/ThorBuzz/FWeb
    branch: main # Or master, whichever is your primary branch
    
    # Build & Start Commands
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    
    # CORRECT STRUCTURE: The 'disks' key is a property of the service.
    # It should be at the same indentation level as 'name', 'env', etc.
    disks:
      - name: fecesa-db-disk
        mountPath: /var/data
        sizeGB: 1
        
    # Environment Variables
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      
      - key: SECRET_KEY
        generateValue: true # Render will create a secure, random value
      
      # This variable points to the database file on the disk defined above.
      - key: DATABASE_URL
        value: "sqlite:////var/data/fecesa_admin.db"