# The version of the Blueprint specification.
version: 1

# Define all the resources for your application
resources:
  # A persistent disk to store your SQLite database
  - name: fecesa-db-disk
    type: disk
    # The properties for the disk
    properties:
      sizeGB: 1 # 1 GB is plenty for a SQLite database

  # Your Flask Web Service
  - name: fweb
    type: web
    # The environment for the service
    env: python
    # Link to the repository
    repo: https://github.com/ThorBuzz/FWeb
    branch: main # Or master, whichever is your primary branch
    # Properties for the web service
    properties:
      # Build & Start Commands
      buildCommand: |
        pip install -r requirements.txt
        # This command creates the database on every build
        python -c "from app import app, db; app.app_context().push(); db.create_all()"
      startCommand: "gunicorn app:app"
      
      # Health Check Path
      healthCheckPath: /
      
      # Environment Variables
      envVars:
        - key: PYTHON_VERSION
          value: "3.11"
        - key: SECRET_KEY
          generateValue: true # Render will generate a secure key for you
        - key: DATABASE_URL
          # This value comes from the disk we defined above
          fromDisk:
            name: fecesa-db-disk
            path: fecesa_admin.db
            
      # This section attaches the disk to your web service
      disks:
        - name: fecesa-db-disk # Must match the disk name above
          mountPath: /var/data # The directory where the disk will be available

# This section tells Render when to apply these changes
previews:
  - fromBranch: main # Or master
    # All resources defined above will be deployed when you push to this branch
    resources:
      - resource: fecesa-db-disk
      - resource: fweb