services:
  # A Web Service for your Flask application
  - type: web
    name: fweb
    env: python
    repo: https://github.com/ThorBuzz/FWeb
    branch: main # Or master, whichever is your primary branch
    
    # --- Build & Start Commands ---
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    
    # --- Persistent Disk for SQLite Database ---
    disks:
      - name: fecesa-db-disk
        mountPath: /var/data
        sizeGB: 1
        
    # --- Environment Variables ---
    envVars:
      # CORRECT WAY TO SET THE PYTHON VERSION
      - key: PYTHON_VERSION
        value: "3.11"
        
      # Secret key will be generated automatically by Render
      - key: SECRET_KEY
        generateValue: true
        
      # Database path on the persistent disk
      - key: DATABASE_URL
        value: "sqlite:////var/data/fecesa_admin.db"