# A simple configuration that works on Render's free tier.
# NOTE: The database will be temporary (ephemeral) with this setup.
services:
  # Define your Flask Web Service
  - type: web
    name: fweb
    env: python
    repo: https://github.com/ThorBuzz/FWeb
    branch: main # Or master, whichever is your primary branch
    
    # Build & Start Commands
    buildCommand: |
      pip install -r requirements.txt
      # This command creates the temporary database on every build
      python -c "from app import app, db; app.app_context().push(); db.create_all()"
    startCommand: "gunicorn app:app"
    
    # Health Check Path
    healthCheckPath: /
        
    # Environment Variables
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure key for you
      # Note: We are not using a disk, so the database path is a standard relative path.
      # This file will be created in the instance's temporary storage.
      - key: DATABASE_URL
        value: "sqlite:///fecesa_admin.db"