# Top-level key for defining persistent disks
disks:
  - name: fecesa-db-disk      # A unique name for this disk resource
    mountPath: /var/data     # The directory where the disk will be available
    sizeGB: 1                # The size of the disk

# Top-level key for defining services (like your web app)
services:
  # A Web Service for your Flask application
  - type: web
    name: fweb
    env: python
    repo: https://github.com/ThorBuzz/FWeb
    branch: main # Or master, whichever is your primary branch
    
    # Build & Start Commands
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    
    # Environment Variables
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      
      - key: SECRET_KEY
        generateValue: true # Render will create a secure, random value
      
      # This variable is the "bridge" to the disk.
      # Its path MUST match the mountPath defined in the disks section above.
      - key: DATABASE_URL
        value: "sqlite:////var/data/fecesa_admin.db"